AllCops:
  Exclude:
    - 'db/**/*'
    - 'lib/**/*'
    - 'fixtures/*'
    - 'active_designer/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

  # rubocop:disable <method>

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
