AllCops:
  Exclude:
    - 'db/**/*'
    - 'lib/tasks/*'
  # rubocop:disable <method>

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
