AllCops:
  Exclude:
    - 'db/**/*'
    - 'lib/**/*'
    - 'fixtures/*'
    - 'active_designer/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

  # rubocop:disable <method>
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/users_controller.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/features/user/user_can_bookmark_a_video_spec.rb'
    - 'spec/factories/tutorials.rb'
    - 'spec/features/vistors/visitor_is_asked_to_log_in_when_bookmarking_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
